const airlineCodes = {
  AS: "Alaska Airlines",
  AA: "American Airlines",
  CO: "Continental Airlines",
  DL: "Delta Air Lines",
  NW: "Northwest Airlines",
  AC: "Air Canada",
  UA: "United Airlines",
  LH: "Lufthansa Cargo AG",
  FX: "FedEx",
  KA: "Hong Kong Dragon Airlines Limited",
  AZ: "Alitalia-Compagnia Aerea Italiana S.P.",
  AF: "Air France",
  SB: "Air Caledonie International",
  KL: "KLM Royal Dutch Airlines",
  MS: "EgyptAir",
  PR: "Philippine Airlines, Inc.",
  QF: "Qantas Airways Ltd.",
  NZ: "Air New Zealand Ltd.",
  IR: "Iran Air",
  AI: "Air India Ltd.",
  AY: "Finnair O/Y",
  SK: "Scandinavian Airlines System (SAS)",
  BA: "British Airways P.L.C.",
  GA: "Garuda Indonesia",
  JL: "Japan Airlines Co. Ltd.",
  AM: "Aeromexico",
  CX: "Cathay Pacific Airways Ltd.",
  CV: "Cargolux Airlines Int’l S.A.",
  EK: "Emirates Sky Cargo",
  KE: "Korean Air Lines Co., Ltd.",
  NH: "All Nippon Airways Co., Ltd.",
  PK: "Pakistan Int’l Airlines",
  TG: "Thai Airways Int’l Public Co., Ltd.",
  MH: "Malaysia Airlines System Berhad",
  TK: "Turkish Airlines Inc.",
  TN: "Air Tahiti Nui",
  HY: "Uzbekistan Airways",
  OS: "Austrian Airlines AG",
  FJ: "Air Pacific (Fiji)",
  RA: "Royal Nepal Airlines Corp.",
  LD: "AHK Air Hong Kong Ltd.",
  OM: "MIAT-Mongolian Airlines",
  CI: "China Airlines Ltd.",
  PO: "Polar Air Cargo Inc.",
  "5X": "United Parcel Service (UPS)",
  SU: "Aeroflot Russian Airlines",
  H8: "Dalavia Far East Airways",
  UL: "SriLankan Airlines Ltd.",
  SQ: "Singapore Airlines Ltd.",
  PX: "Air Niugini Pty Ltd.",
  EG: "Japan Asia Airways Co., Ltd.",
  BR: "EVA Airways Corp.",
  LX: "Swiss Int’l Air Lines Ltd.",
  VN: "Vietnam Airlines",
  EL: "Air Nippon Co., Ltd.",
  FM: "Shanghai Airlines Co., Ltd.",
  MU: "China Eastern Airlines",
  CZ: "China Southern Airlines",
  VS: "Virgin Atlantic",
  KZ: "Nippon Cargo Airlines",
  OZ: "Asiana Airlines Inc.",
  CA: "Air China Ltd.",
};

export default airlineCodes;
